package types

// ADSError is a map of ADS error codes to their messages.
// Source: Beckhoff InfoSys
var ADSError = map[uint32]string{
	0:    "No error",
	1:    "Internal error",
	2:    "No Rtime",
	3:    "Allocation locked memory error",
	4:    "Insert mailbox error",
	5:    "Wrong receive HMSG",
	6:    "Target port not found",
	7:    "Target machine not found",
	8:    "Unknown command ID",
	9:    "Bad task ID",
	10:   "No IO",
	11:   "Unknown ADS command",
	12:   "Win 32 error",
	13:   "Port not connected",
	14:   "Invalid ADS length",
	15:   "Invalid AMS Net ID",
	16:   "Low Installation level",
	17:   "No debug available",
	18:   "Port disabled",
	19:   "Port already connected",
	20:   "ADS Sync Win32 error",
	21:   "ADS Sync Timeout",
	22:   "ADS Sync AMS error",
	23:   "ADS Sync no index map",
	24:   "Invalid ADS port",
	25:   "No memory",
	26:   "TCP send error",
	27:   "Host unreachable",
	28:   "Invalid AMS fragment",
	1280: "No locked memory can be allocated",
	1281: "The size of the router memory could not be changed",
	1282: "The mailbox has reached the maximum number of possible messages. The current sent message was rejected",
	1283: "The mailbox has reached the maximum number of possible messages.",
	1284: "Unknown port type",
	1285: "Router is not initialized",
	1286: "The desired port number is already assigned",
	1287: "Port not registered",
	1288: "The maximum number of Ports reached",
	1289: "Invalid port",
	1290: "TwinCAT Router not active",
	1792: "General device error",
	1793: "Service is not supported by server",
	1794: "Invalid index group",
	1795: "Invalid index offset",
	1796: "Reading/writing not permitted",
	1797: "Parameter size not correct",
	1798: "Invalid parameter value(s)",
	1799: "Device is not in a ready state",
	1800: "Device is busy",
	1801: "Invalid context (must be in Windows)",
	1802: "Out of memory",
	1803: "Invalid parameter value(s)",
	1804: "Not found (files, ...)",
	1805: "Syntax error in command or file",
	1806: "Objects do not match",
	1807: "Object already exists",
	1808: "Symbol not found",
	1809: "Symbol version invalid",
	1810: "Server is in invalid state",
	1811: "AdsTransMode not supported",
	1812: "Notification handle is invalid",
	1813: "Notification client not registered",
	1814: "No more notification handles",
	1815: "Size for watch too big",
	1816: "Device not initialized",
	1817: "Device has a timeout",
	1818: "Query interface failed",
	1819: "Wrong interface required",
	1820: "Class ID is invalid",
	1821: "Object ID is invalid",
	1822: "Request is pending",
	1823: "Request is aborted",
	1824: "Signal warning",
	1825: "Invalid array index",
	1826: "Symbol not active",
	1827: "Access denied",
	1828: "Missing license",
	1829: "License expired",
	1830: "License exceeded",
	1831: "License invalid",
	1832: "License invalid system id",
	1833: "License not time limited",
	1834: "License issue time in the future",
	1835: "License time period to long",
	1836: "Exception occured during system start",
	1837: "License file read twice",
	1838: "Invalid signature",
	1839: "Public key certificate",
	1856: "Error class <client error>",
	1857: "Invalid parameter at service",
	1858: "Polling list is empty",
	1859: "Var connection already in use",
	1860: "Invoke ID in use",
	1861: "Timeout elapsed",
	1862: "Error in win32 subsystem",
	1863: "Invalid client timeout value",
	1864: "Ads-port not opened",
	1872: "Internal error in ads sync",
	1873: "Hash table overflow",
	1874: "Key not found in hash",
	1875: "No more symbols in cache",
	1876: "Invalid response received",
	1877: "Sync port is locked",
	4096: "Internal fatal error in the TwinCAT real-time system",
	4097: "Timer value not vaild",
	4098: "Task pointer has the invalid value ZERO",
	4099: "Task stack pointer has the invalid value ZERO",
	4100: "The demand task priority is already assigned",
	4101: "No more free TCB (Task Control Block) available. Maximum number of TCBs is 64",
	4102: "No more free semaphores available. Maximum number of semaphores is 64",
	4103: "No more free queue available. Maximum number of queue is 64",
	4109: "An external synchronization interrupt is already applied",
	4110: "No external synchronization interrupt applied",
	4111: "The apply of the external synchronization interrupt failed",
	4112: "Call of a service function in the wrong context",
	4119: "Intel VT-x extension is not supported",
	4120: "Intel VT-x extension is not enabled in system BIOS",
	4121: "Missing function in Intel VT-x extension",
	4122: "Enabling Intel VT-x fails",
}
